### ISSUE TITLE
Width of Folder and Files Panel could be resizable

### ISSUE THREAD

**Issue by jswiderski** [ckfinder/ckfinder#399]
Often it happens that creates a folder with a longer name which can't be viewed in full in Folder Panel. While we have the https://ckeditor.com/docs/ckfinder/ckfinder3/#!/api/CKFinder.Config-cfg-primaryPanelWidth setting it would be nice if the resize could be made dynamically - just by dragging the border between two panels.

**Comment by jodator** [comment]
There's a hint from a requester that this:

```css
 .ckf-ui-mode-desktop .ckf-folders-panel.ui-panel-closed.ckf-folders-panel-default {
    width: min-content !important;
    position: relative;
}
```

will auto adjust the width depending on content which produce similar results if anyone interested.
